// ============================================================
// ABROAD — Spring '26 trip tracker data
// Edit everything here: copy, highlights, photos, coordinates.
// Photos live in /public/photos — filenames referenced below.
// Missing photos fall back to a styled placeholder automatically.
// ============================================================

export const META = {
  name: 'ETHAN GOLDSTEIN',
  title: 'ABROAD',
  subtitle: 'A Semester in Motion',
  home: 'Florence, Italy',
  dates: 'JAN 20 — MAY 9, 2026',
  stats: [
    { value: '109', label: 'Days' },
    { value: '8', label: 'Countries' },
    { value: '20+', label: 'Cities' },
    { value: '18', label: 'Weekends' },
  ],
}

export const TRIPS = [
  {
    id: 'florence',
    num: '01',
    month: 'JAN',
    title: 'FLORENCE',
    tag: 'Home Base',
    place: 'Florence, Italy',
    lat: 43.7696,
    lon: 11.2558,
    home: true,
    blurb:
      'Touched down January 20. Duomo views, trattoria dinners, and the city that ran the next 109 days.',
    highlights: ['Home base', 'Duomo', 'Piazzale Michelangelo', 'Trattoria dinners'],
    media: [],
    color: '#59d9ff',
  },
  {
    id: 'tuscany',
    num: '02',
    month: 'JAN',
    title: 'TUSCANY',
    tag: 'Wine Tour',
    place: 'Chianti, Italy',
    lat: 43.545,
    lon: 11.32,
    blurb:
      'First weekend out — rolling vineyards, cellar tours, and a proper education in Chianti Classico.',
    highlights: ['Wine tour', 'Vineyards', 'Cellar tastings', 'Hill towns'],
    media: ['tuscany-1.jpg'],
    color: '#c05a78',
  },
  {
    id: 'rome',
    num: '03',
    month: 'FEB',
    title: 'ROME',
    tag: 'Day Trip',
    place: 'Rome, Italy',
    lat: 41.8902,
    lon: 12.4922,
    blurb:
      'The greatest hits in one sprint — Colosseum, Spanish Steps, and a coin over the shoulder into the Trevi.',
    highlights: ['Colosseum', 'Spanish Steps', 'Trevi Fountain'],
    media: ['rome-1.jpg'],
    color: '#f2a154',
  },
  {
    id: 'pompeii',
    num: '04',
    month: 'FEB',
    title: 'POMPEII & NAPLES',
    tag: 'Under the Volcano',
    place: 'Pompeii, Italy',
    lat: 40.7462,
    lon: 14.4989,
    blurb:
      'Walked a city frozen in 79 AD, then stared down the volcano that buried it.',
    highlights: ['Pompeii ruins', 'Mount Vesuvius', 'Naples'],
    media: ['pompeii-1.jpg'],
    color: '#ff6b4a',
  },
  {
    id: 'milan',
    num: '05',
    month: 'FEB',
    title: 'MILAN',
    tag: 'Winter Olympics',
    place: 'Milan, Italy',
    lat: 45.4642,
    lon: 9.19,
    blurb:
      'Caught the Milano–Cortina 2026 Winter Games energy in the fashion capital of the world.',
    highlights: ['2026 Winter Olympics', 'Olympic crowds', 'Duomo di Milano'],
    media: [
      'milan-1.jpg',
      { src: 'milan-2.mp4', type: 'video' },
    ],
    color: '#9ecbff',
  },
  {
    id: 'switzerland',
    num: '06',
    month: 'FEB',
    title: 'SWITZERLAND',
    tag: 'Snowboarding',
    place: 'Swiss Alps',
    lat: 46.82,
    lon: 8.403,
    blurb:
      'Snowboarding down the Swiss Alps with views that did not look real.',
    highlights: ['Swiss Alps', 'Snowboarding', 'Mountain views'],
    media: ['switzerland-1.jpg'],
    color: '#8ef0d2',
  },
  {
    id: 'paris',
    num: '07',
    month: 'MAR',
    title: 'PARIS',
    tag: 'City of Light',
    place: 'Paris, France',
    lat: 48.8566,
    lon: 2.3522,
    blurb:
      'The Eiffel sparkling on the hour, a boat down the Seine, and dinners worth every euro.',
    highlights: ['Eiffel Tower', 'Seine boat tour', 'Dinners'],
    media: [
      'paris-1.jpg',
      'paris-2.jpg',
    ],
    color: '#ffd166',
  },
  {
    id: 'london',
    num: '08',
    month: 'MAR',
    title: 'LONDON',
    tag: 'Match Day',
    place: 'London, England',
    lat: 51.5074,
    lon: -0.1278,
    blurb:
      'Stamford Bridge for Chelsea v Burnley, and London after dark.',
    highlights: ['Chelsea v Burnley', 'Stamford Bridge', 'Exploring'],
    media: [
      'london-1.jpg',
      'london-2.jpg',
    ],
    color: '#7aa2ff',
  },
  {
    id: 'bologna',
    num: '09',
    month: 'MAR',
    title: 'BOLOGNA',
    tag: 'Day Trip w/ Dohan',
    place: 'Bologna, Italy',
    lat: 44.4949,
    lon: 11.3426,
    blurb:
      'Markets, wine, and wandering the porticoes with Dohan.',
    highlights: ['Markets', 'Wine', 'Exploring'],
    media: ['bologna-1.jpg'],
    color: '#e0854a',
  },
  {
    id: 'springbreak',
    num: '10',
    month: 'MAR',
    title: 'SPRING BREAK',
    tag: 'The Boys Pull Up',
    place: 'Florence, Italy',
    lat: 43.82,
    lon: 11.42,
    blurb:
      'The boys flew in and Florence became home base — with runs to Venice and Rome. One week, nonstop.',
    highlights: ['Venice canals', 'Florence tour-guide duty', 'Rome round two'],
    media: [
      'springbreak-1.jpg',
      'springbreak-2.jpg',
      'springbreak-3.jpg',
    ],
    color: '#6ee7b7',
  },
  {
    id: 'prague',
    num: '11',
    month: 'APR',
    title: 'PRAGUE',
    tag: 'Bohemia',
    place: 'Prague, Czech Republic',
    lat: 50.0755,
    lon: 14.4378,
    blurb:
      'Chimney cakes, castle views over the river, and markets worth the walk.',
    highlights: ['Prague Castle', 'Chimney cakes', 'Markets', 'Old Town'],
    media: [
      'prague-1.jpg',
      'prague-2.jpg',
      'prague-3.jpg',
    ],
    color: '#d4a5ff',
  },
  {
    id: 'amsterdam',
    num: '12',
    month: 'APR',
    title: 'AMSTERDAM',
    tag: 'Canals & Concerts',
    place: 'Amsterdam, Netherlands',
    lat: 52.3676,
    lon: 4.9041,
    blurb:
      'Canals, a Gunna show, and a city best seen from the water. Amsterdam did not miss.',
    highlights: ['Gunna concert', 'Canal cruise', 'Exploring'],
    media: [
      'amsterdam-1.jpg',
      'amsterdam-2.jpg',
      'amsterdam-3.jpg',
    ],
    color: '#ff5d8f',
  },
  {
    id: 'timeout',
    num: '13',
    month: 'APR',
    title: 'TIME OUT',
    tag: 'Stayed Put',
    place: 'Florence, Italy',
    lat: 43.7696,
    lon: 11.2558,
    noPin: true,
    blurb:
      'The one weekend the map did not move. Florence, slow mornings, gelato.',
    highlights: ['No travel', 'Florence off-duty'],
    media: ['timeout-1.jpg'],
    color: '#8b95b5',
  },
  {
    id: 'pisa',
    num: '14',
    month: 'APR',
    title: 'CASTIGLIONCELLO & PISA',
    tag: 'Coast Day',
    place: 'Tuscan Coast, Italy',
    lat: 43.7228,
    lon: 10.4017,
    blurb:
      'Beach morning in Castiglioncello, obligatory Leaning Tower pic by afternoon. One day, two towns.',
    highlights: ['Beach', 'Leaning Tower of Pisa', 'Same-day double'],
    media: [
      'pisa-1.jpg',
      'pisa-2.jpg',
    ],
    color: '#ffe08a',
  },
  {
    id: 'family',
    num: '15',
    month: 'APR',
    title: 'FAMILY WEEK',
    tag: 'Mom & Michelle Visit',
    place: 'Rome & Florence, Italy',
    lat: 41.9029,
    lon: 12.4534,
    blurb:
      'Mom and Michelle came through — Vatican to the Jewish Ghetto, pasta-making class, Michelangelo\'s David, and the best affogato in Florence.',
    highlights: [
      'Vatican',
      'Jewish Ghetto & Synagogue',
      'Colosseum',
      'Trevi & Spanish Steps',
      'Pasta-making class',
      "Michelangelo's David",
      'Osteria della Ponche',
      'Affogato',
      'SMN fragrance & shopping',
      'Vespe Café',
    ],
    media: [
      'family-1.jpg',
      'family-2.jpg',
      'family-3.jpg',
    ],
    color: '#f7797d',
  },
  {
    id: 'morocco',
    num: '16',
    month: 'MAY',
    title: 'MOROCCO',
    tag: 'Sahara',
    place: 'Merzouga & Aït Benhaddou',
    lat: 31.0994,
    lon: -4.0084,
    blurb:
      'Rode camels into the Sahara at sunset, boarded the dunes, and camped under a sky full of stars.',
    highlights: [
      'Camel ride at sunset',
      'GOT / Gladiator / OBX castle',
      'Sandboarding',
      'ATVs on the dunes',
      'Desert camping',
      'Sunrise & sunset',
      'Green turban scarf',
      'Blue rug hoodie',
    ],
    media: [
      'morocco-1.jpg',
      'morocco-2.jpg',
      'morocco-3.jpg',
      'morocco-4.jpg',
      'morocco-5.jpg',
      'morocco-6.jpg',
    ],
    color: '#ff8a3c',
  },
  {
    id: 'malta',
    num: '17',
    month: 'MAY',
    title: 'MALTA',
    tag: 'Island Time',
    place: 'Valletta, Malta',
    lat: 35.8989,
    lon: 14.5146,
    blurb:
      'Boat cruise around the island, beach days, and long dinners by the water.',
    highlights: ['Boat cruise', 'Beach', 'Dinner', 'Valletta'],
    media: [
      'malta-1.jpg',
      'malta-2.jpg',
      'malta-3.jpg',
      'malta-4.jpg',
      'malta-5.jpg',
    ],
    color: '#4cc9f0',
  },
  {
    id: 'amalfi',
    num: '18',
    month: 'MAY',
    title: 'AMALFI COAST',
    tag: 'The Finale',
    place: 'Amalfi & Capri, Italy',
    lat: 40.634,
    lon: 14.6027,
    blurb:
      'Closed it out in a cliffside villa with 30 people — boat cruise to Capri, pool days, one last sunset over the Tyrrhenian.',
    highlights: ['30-person villa', 'Boat cruise', 'Capri', 'Pool days', 'Dinners out'],
    media: [
      'amalfi-1.jpg',
      'amalfi-2.jpg',
      'amalfi-3.jpg',
      { src: 'amalfi-4.mp4', type: 'video' },
    ],
    color: '#57cc99',
  },
]

// Pinned trips in order = the route the camera (and the drawn
// flight path) follows. The stay-put week keeps the camera home.
export const ROUTE = TRIPS.filter((t) => !t.noPin)
